services:
  procpag:
    image: docker.io/erickemprobr/procpag:latest 
    platform: linux/amd64
    ports: 
    - "8089:8089"
    networks:
    - fase3net

  auth-db:
    image: mysql:8.0
    container_name: auth-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: authdb
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
    ports:
      - "3307:3306"
    volumes:
      - auth_db_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - fase3net

  auth-service:
    build: ./auth-service
    container_name: auth-service
    restart: always
    depends_on:
      auth-db:
        condition: service_healthy
    ports:
      - "8081:8081"
    environment:
      SERVER_PORT: 8081
      JWT_SECRET: "ZGlmZmljdWx0eWZsYWdjbG9ja2NvbXBvdW5kYXV0aG9yc3BpZGVyZGl2aWRld3JhcHA="
      SPRING_DATASOURCE_URL: jdbc:mysql://auth-db:3306/authdb
      SPRING_DATASOURCE_USERNAME: dev
      SPRING_DATASOURCE_PASSWORD: dev
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - fase3net

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - fase3net

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks:
      - fase3net

  payment-service:
    build: ./payment-service
    container_name: payment-service
    restart: always
    depends_on:
      kafka:
        condition: service_started
    ports:
      - "8083:8083"
    environment:
      SERVER_PORT: 8083
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      PROCPAG_URL: http://procpag:8089
    networks:
      - fase3net

networks:
  fase3net:

volumes:
  auth_db_data:
